### ISSUE TITLE
windows tests failing because no oq.exe 

### ISSUE THREAD

**Issue by CB-quakemodel** [GEMScienceTools/oq-mbtk#383]
The windows tests are failing because oq.exe is not recognised as a cmd. Also occuring for some tests on oq-engine github. Assigning as requested by @vot4anto

![image](https://github.com/GEMScienceTools/oq-mbtk/assets/119606956/bb1f8a89-0e61-431d-a429-8b701f1bd6b1)

**Comment by vot4anto** [comment]
https://github.com/python/cpython/issues/100171
