### ISSUE TITLE
Missing Mmax calculation from trace length in fault modeler

### ISSUE THREAD

**Issue by klunk386** [GEMScienceTools/oq-mbtk#71]
@klunk386 @julgp @mmpagani please review:

So far, the code creates an MFD using a user-defined Mmax or the default value. It would be desirable to have a method that computes Mmax from the fault trace length (as it was in the previous code). Then, the user-defined Mmax (or the default) should be used only when trace-specific value exceed this.

**Comment by cossatot** [comment]
As Marco wrote in the email, Mmax is calculated from the fault area if a separate value is not given.  

This is already implemented in the new library code very similarly to the old code, with the default/override options available in the new code

Look at the `get_M_max` function in the `fault_conversion_utils`:

```python
def get_M_max(fault_dict, mag_scaling_rel=None, area_method='simple',
              width_method='seismo_depth', width_scaling_rel='leonard_2010',
              defaults=defaults, param_map=param_map):


    """
    Calculates (or fetches) the maximum magnitude for a fault, given a fault
    attribute, the fault geometry and a scaling relationship, or a project
    default.
    The priority order is:
        1- Fault attribute.
        2- Fault geometry and scaling relationship.
        3- Default value.
    ...
    """

    # TODO: check if fault M_max is greater than zone M_max
    try:
        M_max = fault_dict[param_map['M_max']]

    except KeyError:
        try:
            # fetch?
            if mag_scaling_rel is None:
                mag_scaling_rel = defaults['mag_scaling_rel']

            rake = get_rake(fault_dict)
            fault_area = get_fault_area(fault_dict, area_method=area_method,
                                        width_method=width_method,
                                        width_scaling_rel=width_scaling_rel,
                                        defaults=defaults, param_map=param_map)

            M_max = mag_scaling_rel.get_median_mag(fault_area, rake)

        except:
            M_max = defaults['M_max']

return M_max
```

This is the function that is called by `calc_mfd_from_fault_params` if `M_max` is not passed directly as an argument to `calc_mfd_from_fault_params` (I think it would only be passed for sensitivity testing or special cases).

**Comment by klunk386** [comment]
Yes, sorry, I've probably express myself poorly.
What it is missing here is exactly what it is written in the comment (# TODO: check if fault M_max is greater than zone M_max).
I mean, there should be an option to limit the Mmax computed directly from the fault with an uppermost Mmax limit. Above this value the user-defined or hardcoded Mmax should be used, while below the fault-specific is kept.
As it is now (if I'm not mistaking) if you pass a defult Mmax, this will always replace the one computed from the area, even for small faults. For example, now a fault capable to generate only a 6.8, will always use the default, which is 8 (or more).

**Comment by cossatot** [comment]
> As it is now (if I'm not mistaking) if you pass a defult Mmax, this will always replace the one computed from the area, even for small faults. For example, now a fault capable to generate only a 6.8, will always use the default, which is 8 (or more).

No, this isn't true.  In the documentation string for the function, it states:
```
    The priority order is:
        1- Fault attribute.
        2- Fault geometry and scaling relationship.
        3- Default value.
``
The default value is only used if 1) there is no `M_max` in the `fault_dict` and 2) the calculation of `M_max` by fault area fails for some reason.  The default value should not be put in the `fault_dict` during the model building process--it should be kept separate for this exact reason.

When I wrote the TODO,  I was intending something a slightly different:  It is to check whether a fault lies within a specific area source zone (polygon) that has a different `M_max`, of which there may be many in a project, so the zone M_max won't be the same as a default value.  This would require a new parameter (`zone_M_max`) that is not currently present.  I will work on adding this to the code.

**Comment by mmpagani** [comment]
Although I perhaps understand the rationale, I don’t think is good 
practice to change the Mmax value for a fault arbitrarily.

**Comment by klunk386** [comment]
I have proposed the following modification:

`def get_M_max(fault_dict, mag_scaling_rel=None, area_method='simple',
              width_method='seismo_depth', width_scaling_rel='leonard_2010',
              defaults=defaults, param_map=param_map):
    """
    Calculates (or fetches) the maximum magnitude for a fault, given a fault
    attribute, the fault geometry and a scaling relationship, or a project
    default.

    The priority order is:
        1- Fault attribute.
        2- Default value if not none
        3- Fault geometry and scaling relationship, if lower than M_upp
           otherwise use M_upp
        ...
    """

    # TODO: check if fault M_max is greater than zone M_max
    try:
        M_max = fault_dict[param_map['M_max']]

    except KeyError:
        if defaults['M_max'] is not None:
            M_max = defaults['M_max']

        else:
            # fetch?
            if mag_scaling_rel is None:
                mag_scaling_rel = defaults['magnitude_scaling_relationship']

            rake = get_rake(fault_dict) #returns mle rake
            fault_area = get_fault_area(fault_dict, area_method=area_method,
                                        width_method=width_method,
                                        width_scaling_rel=width_scaling_rel,
                                        defaults=defaults, param_map=param_map)

            M_max = mag_scaling_rel.get_median_mag(fault_area, rake)

            try:
                M_upp = fault_dict[param_map['M_upp']]

            except KeyError:
                M_upp = defaults['M_upp']

            if M_max > M_upp:
                M_max = M_upp

    return M_max`

Clearly, the default dictionary should be modified as well by including:

`'M_max': None, 'M_upp': 10.,`

As @mmpagani said, it is important to keep M_max as None by default, so that the calculation using geometry attributes has always higher priority. M_max, then, will be override only if explicitly stated by the user (for whatever reason, testing or so)

**Comment by cossatot** [comment]
Thanks Valerio, this is great.

I have two minor suggestions:

1. `M_upp` should be `M_upper` (or at least `M_up`).  I think that `M_upper` is the most clear and readable. While it is possible to infer what `M_upp` means, it is very clear what `M_upper` is.

2. Instead of 

```python
try:
    M_upp = fault_dict[param_map['M_upp']]
except:
    M_upp = defaults['M_upp']
```

just do

```python
M_upp = fetch_param_val(fault_dict, 'M_upp', param_map=param_map)
```
 
The second does the same as the first but is cleaner, and when I make changes (adding logging, moving the `param_map` to the interface, etc.) I only have to do it to the one function instead of digging through the entire code base to find every instance of this pattern.

Grazie mille!

**Comment by cossatot** [comment]
Also, just as a quick discussion point about the usage of the `M_max` fault attribute (not about the code):

When I am making the fault databases, it happens sometimes that faults that I have mapped have had large earthquakes in the historical or instrumental record; these may be larger than expected based on global scaling relationships. For example in the Northeastern Asia fault database, some faults in western Mongolia have had earthquakes that are ~8.1-8.4 even though scaling relationships would give them `M_max` values of ~7.8-7.9.  Currently I will just list something like this in the notes for the fault, but with the new library (including this feature) I can now add the `M_max` directly to those faults so that we can be sure the hazard model will correctly incorporate the observations.  My point is that it is not always an 'arbitrary' modification, and not only for testing purposes.

**Comment by klunk386** [comment]
Thank Richard, I have included this modifications just now and will push 
it in a moment.

We are now working on including the LSD threshold constrain.

Cheers,
V&J

Il 02/08/2018 16:21, Richard Styron ha scritto:

**Comment by mmpagani** [comment]
Valerio can you pls install a pep8 checker in your editor? Your code does not seem to comply with it. Uppercase letter for variables is bad practice. Thanks

**Comment by cossatot** [comment]
Marco,

I wrote the code that has `M_max` as a variable. I have only done it this way because `M` for magnitude is usually capitalized, so scientific usage for me has priority over code convention.  We can change this if it is confusing.
