### ISSUE TITLE
to include a exporter to modified geojson

### ISSUE THREAD

**Issue by julgp** [GEMScienceTools/oq-mbtk#73]
Taking into account that we could modified the original [input] geojson, can be useful to add a method to export the modified geojson to a new file.

**Comment by cossatot** [comment]
Julio, this is a good idea and should be pretty easy. 

What would you like to see, and what kind of format?

For example, do we want to export values as tuples or as floats? Do we want to include slip rates, MFDs, or both?

**Comment by klunk386** [comment]
This has been implemented in the `fault_database` class as `export_to_geojson` method.
At the moment, the exported geojson includes all keywords translated according to the parameter mapping (while all keywords not in the param_map are kept as they are). If there is a need to preserve the original keywords, however, let me know.
From here we can extend adding more functionalities.
