### ISSUE TITLE
Incorrect earthquake occurrence rates for EvenlyDiscretizedMFD if `M_max` is not on bin edge

### ISSUE THREAD

**Issue by cossatot** [GEMScienceTools/oq-mbtk#75]
I have been investigating inconsistencies in the annual moment release rates and annual moment accumulation rates (i.e. from fault area, slip rate and rigidity) that we have seen in some of the fault source models.

I have found an issue that produces incorrect rates, particularly when `M_max` of a fault is less than 1 bin width above `M_min`. In this instance, the occurrence rates can be __2 orders of magnitude__ above the accurate rates (i.e. the moment accumulation rate). The issue is less severe with higher `M_max` but never goes away completely:

![image](https://user-images.githubusercontent.com/2835718/43476441-72f02a64-94ad-11e8-9b03-426ca02d8575.png)

A correct moment release rate would be constant regardless of `M_max` because it would balance the moment accumulation rate (disregarding any aseismic slip, etc., which is handled before the MFD calculation).

I investigated the problem and have reproduced it in a Jupyter Notebook [here](https://gist.github.com/cossatot/5c21bc1f6bc26f47763e6c835cf6da58).  In the notebook, I have proposed a correction that is essentially rounding up the `M_max` to the edge of the current bin (plus a few tiny patches to other functions).

The correction is evident here: 

![image](https://user-images.githubusercontent.com/2835718/43476683-06cb7db0-94ae-11e8-9a72-690ca4f53217.png)

The corrected moment release rate is invariant to `M_max` and equals the moment accumulation rate.

If we approve of the correction, I will make a pull request for it. Otherwise we can discuss what other solutions there are, but the issue is causing some big problems for small faults in the current hazard models.

**Comment by mmpagani** [comment]
Thanks for this thorough check. I'm happy with the suggested changes. I think you should create a PR for this.
