### ISSUE TITLE
Lower seismogenic depth

### ISSUE THREAD

**Issue by klunk386** [GEMScienceTools/oq-mbtk#79]
Presently, the function `leonard_width_from_length` uses a maximum width of 150 for non strike-slip faults, which produces very large low seismogenic depths for dip values larger than e.g. > 40.
As we discussed previously, it would be very useful to limit the generated width in order not to exceed a threshold lower seismogenic depth value (default or user provided).
Actually, such threshold should be used for any method to calculate the width, not only Leonard.

**Comment by klunk386** [comment]
We have included a threshold check at the end of `calc_fault_width_from_length`.
So far, the modification seems to be working properly, but we need to implement an ad-hoc test.

**Comment by cossatot** [comment]
Valerio, I agree that the threshold should apply to all width methods.

There are a few tests on calculating the widths in the formal unit tests.  It should be very easy to copy then modify these tests.
